controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

refresh_token:
    path: /token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
