controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# app_login:
    # path: /login

# app_register:
    # path: /register
