# ==== CONFIGURE =====
# Stage 1
FROM node:18.16.1-alpine as build
# Setting up the work directory
WORKDIR /usr/src/app
COPY package.json .
# COPY yarn.lock .
RUN yarn install
COPY . .
# RUN yarn build
# RUN yarn postbuild

# Stage 2
FROM nginx:1.25
ENV NODE_ENV development
COPY nginx_local.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/htmlFdev