version: '3.8'
services:
  client:
    image: client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    env_file: .env
    # volumes:
    #   - ./client/certs:/etc/ssl/private:ro
    ports:
      - "3000:3000"