security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        login:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        app_register:
            pattern: ^/register
            stateless: true

        app_login:
            pattern: ^/login
            stateless: true
            json_login:
                provider: login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        refresh:
            pattern:  ^/token/refresh
            stateless: true
        main:
            pattern: ^/
            stateless: true
            provider: login
            jwt: ~
            entry_point: jwt
            refresh_jwt:
                check_path: /token/refresh
    access_control:
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/docs, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
